server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: douyin_java
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/douyin?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: wjh990923
  redis:
    host: localhost
    port: 6379
    #password: root@123456
    database: 0
    cache:
      redis:
        time-to-live: 1800000 #设置缓存数据的过期时间

mybatis:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true

douyin:
  imagePath: G:\3120210430Jinghao1\ByteDance\image\
  videoPath: G:\3120210430Jinghao1\ByteDance\video\